### ISSUE TITLE
为何在频道管理在添加新频道又做删除的时候有问题

### ISSUE THREAD

**Issue by littleViolence** [oubowu/OuNews#10]
删除了新增的频道界面没有刷新还会保留被删除的频道,而且感觉加载频道管理的所有频道比较慢,会出现奔溃的情况.
10-26 02:13:17.545 2874-2874/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.oushangfeng.ounews.debug, PID: 2874
                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                  Caused by: rx.exceptions.OnCompletedFailedException: Attempt to invoke interface method 'void com.oushangfeng.ounews.base.BaseView.hideProgress()' on a null object reference
                                                     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:85)
                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
                                                     at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:284)
                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.oushangfeng.ounews.base.BaseView.hideProgress()' on a null object reference
                                                     at com.oushangfeng.ounews.base.BasePresenterImpl.requestComplete(BasePresenterImpl.java:52)
                                                     at com.oushangfeng.ounews.module.news.model.INewsChannelInteractorImpl$1.onCompleted(INewsChannelInteractorImpl.java:160)
                                                     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68) 
                                                     at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225) 
                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:284) 
                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219) 
                                                     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by oubowu** [comment]
可以把详细操作步骤列下吗？
