### ISSUE TITLE
NullPointerException Crash

### ISSUE THREAD

**Issue by LoveqLRC** [oubowu/OuNews#16]
```
FATAL EXCEPTION: main
                                                                            Process: com.oushangfeng.ounews.debug, PID: 4043
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
                                                                                at com.oushangfeng.ounews.module.news.ui.NewsDetailActivity.onClick(NewsDetailActivity.java:236)
                                                                                at android.view.View.performClick(View.java:4792)
                                                                                at android.view.View$PerformClick.run(View.java:19938)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5671)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
点击新闻的时候，当数据还没加载出来，点击黄色图片按钮`crash`

**Comment by LoveqLRC** [comment]
顺便问一下，bean包下的类是插件生成还是手打的 ... ...

**Comment by oubowu** [comment]
插件生成的 估计是网络设置了才去设置imageview的tag导致的空指针了

**Comment by LoveqLRC** [comment]
什么插件，我只用过`gsonformat`的插件

**Comment by oubowu** [comment]
就是gsonformat

**Comment by oubowu** [comment]
注解那个是gsonformat可以配置的 可以配jackson解析对应的形式

**Comment by LoveqLRC** [comment]
Thanks a lot
