### ISSUE TITLE
在Android5.0版本以上视频播放会崩溃。

### ISSUE THREAD

**Issue by taofaqi** [oubowu/OuNews#3]
测试手机是NUBIA Z9.

**Comment by oubowu** [comment]
是所有视频都奔溃吗 具体有什么提示？

**Comment by taofaqi** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oushangfeng.ounews.debug/com.oushangfeng.ounews.module.video.ui.VideoPlayActivity}: java.lang.NullPointerException: uriString
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                               Caused by: java.lang.NullPointerException: uriString
                                                                                  at android.net.Uri$StringUri.<init>(Uri.java:470)
                                                                                  at android.net.Uri$StringUri.<init>(Uri.java:460)
                                                                                  at android.net.Uri.parse(Uri.java:432)
                                                                                  at io.vov.vitamio.widget.VideoView.setVideoPath(VideoView.java:391)
                                                                                  at com.oushangfeng.ounews.module.video.ui.VideoPlayActivity.playVideo(VideoPlayActivity.java:82)
                                                                                  at com.oushangfeng.ounews.module.video.presenter.IVideoPlayPresenterImpl.<init>(IVideoPlayPresenterImpl.java:20)
                                                                                  at com.oushangfeng.ounews.module.video.ui.VideoPlayActivity.initView(VideoPlayActivity.java:74)
                                                                                  at com.oushangfeng.ounews.base.BaseActivity.onCreate(BaseActivity.java:169)
                                                                                  at android.app.Activity.performCreate(Activity.java:5976)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441) 
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by taofaqi** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oushangfeng.ounews.debug/com.oushangfeng.ounews.module.video.ui.VideoPlayActivity}: java.lang.NullPointerException: uriString
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                               Caused by: java.lang.NullPointerException: uriString
                                                                                  at android.net.Uri$StringUri.<init>(Uri.java:470)
                                                                                  at android.net.Uri$StringUri.<init>(Uri.java:460)
                                                                                  at android.net.Uri.parse(Uri.java:432)
                                                                                  at io.vov.vitamio.widget.VideoView.setVideoPath(VideoView.java:391)
                                                                                  at com.oushangfeng.ounews.module.video.ui.VideoPlayActivity.playVideo(VideoPlayActivity.java:82)
                                                                                  at com.oushangfeng.ounews.module.video.presenter.IVideoPlayPresenterImpl.<init>(IVideoPlayPresenterImpl.java:20)
                                                                                  at com.oushangfeng.ounews.module.video.ui.VideoPlayActivity.initView(VideoPlayActivity.java:74)
                                                                                  at com.oushangfeng.ounews.base.BaseActivity.onCreate(BaseActivity.java:169)
                                                                                  at android.app.Activity.performCreate(Activity.java:5976)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441) 
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by oubowu** [comment]
坑爹的数据，视频网址居然都有空的，我从视频列表传到那里视频播放没有做判空判断所以导致了空指针，已经添加了判空代码上传了，你再试一下

**Comment by oubowu** [comment]
买了新机，6.0系统必死，已找到真正的原因https://github.com/yixia/VitamioBundle/issues/312，这个是vitamio的bug，我把它targetSdkVersion改为22就okay了，大哥你再试下可以不
